Version control: 2026-10-14 - 18:30
Luis Anunciacao, PhD

# DA - AGEM Time Series

Loads `df.rds` from the DP notebook. Nothing is transformed here.

**Tests.** Items are sorted by their smallest p. Two-sided Wilcoxon rank-sum (Mann-Whitney U) tests between consecutive waves, by company, for scale items. Waves are independent samples: SurveyMonkey collected no respondent ID, so answers cannot be paired. Lideres T2 items 6 and 20 are reverse-coded for the tests only (DP §2); counts are raw. "—" = item not applied in that wave. Tables 3-4 repeat Tables 1-2 with the scale responses collapsed to 3 categories (discordo / neutro / concordo; nunca/raramente / as vezes / muitas vezes/sempre); the tests are the same (5-point). Tables 3-4 flag risk items (negatively worded) "(risco)" (DP §2) and drop the questionnaire's "(invertida)" tags.

In [1]:
pacman::p_load(tidyverse)

options(repr.matrix.max.rows = 400, repr.matrix.max.cols = 20)

# DP output from GitHub (Processing and analysis/Importable data/df.rds); private repository, token from the git credential store (gitcreds)
df <- readRDS(gzcon(curl::curl("https://raw.githubusercontent.com/anovabr/AGEM-Time-Series/main/Processing%20and%20analysis/Importable%20data/df.rds",
                               handle = curl::new_handle() |> curl::handle_setheaders(Authorization = paste("token", gitcreds::gitcreds_get()$password)))))

# item x response frequency table by company and wave, with W and p of the rank-sum test (T1 vs T2, T2 vs T3) on the first row of each item;
# items sorted by their smallest p. agrupar = TRUE: counts of the 3-category responses (codigo_3 / resposta_3), risk items (negatively worded) flagged
# "(risco)" (the questionnaire's own "(invertida)" tags on positive items are dropped); the tests always use the 5-point valor_teste
tabela <- function(inst, agrupar = FALSE) {
  d <- filter(df, instrumento == inst) |> mutate(codigo = if (agrupar) codigo_3 else codigo)
  o <- filter(attr(df, "opcoes"), instrumento == inst) |> transmute(item, codigo = if (agrupar) codigo_3 else codigo, resposta = if (agrupar) resposta_3 else resposta) |> distinct()
  o |>
    inner_join(distinct(d, item, empresa, onda), by = "item", relationship = "many-to-many") |>
    left_join(count(d, item, codigo, empresa, onda), by = c("item", "codigo", "empresa", "onda")) |>
    mutate(n = as.character(replace_na(n, 0L))) |>
    bind_rows(d |>
                filter(!is.na(valor_teste)) |>
                reframe(map_dfr(list(c("T1", "T2"), c("T2", "T3")), \(w) if (all(w %in% onda))
                          with(suppressWarnings(wilcox.test(valor_teste[onda == w[1]], valor_teste[onda == w[2]])),
                               tibble(par = paste0(w[1], "→", w[2]), p = p.value,
                                      n = paste0(sprintf("W = %.1f; ", statistic), if_else(p.value < 0.001, "p < 0.001", sprintf("p = %.3f", p.value)))))),
                        .by = c(item, empresa)) |>
                transmute(item, empresa, onda = par, n, p, codigo = 1L)) |>
    mutate(ordem = suppressWarnings(min(p, na.rm = TRUE)), .by = item) |>
    pivot_wider(id_cols = c(item, codigo, ordem), names_from = c(empresa, onda), values_from = n, names_sort = TRUE) |>
    arrange(ordem, item, codigo) |>
    left_join(distinct(d, item, item_texto, risco), by = "item") |>
    left_join(select(o, item, codigo, resposta), by = c("item", "codigo")) |>
    mutate(item_texto = if (agrupar) paste0(str_remove(item_texto, " \\(invertida\\)"), if_else(risco, " (risco)", "")) else item_texto,
           Item = if_else(codigo == 1, paste0(item, ". ", item_texto), ""), Resposta = paste0("(", codigo, ") ", resposta),
           across(-c(item, codigo, ordem, item_texto, risco, resposta, Item, Resposta), ~ if_else(is.na(.) & (!str_detect(cur_column(), "→") | codigo == 1), "—", replace_na(., "")))) |>
    (\(t) select(t, Item, Resposta, all_of(sort(setdiff(names(t), c("item", "codigo", "ordem", "item_texto", "risco", "resposta", "Item", "Resposta"))))))()
}

## §1 Table 1 - Inventário de Saúde Mental exclusivo para Líderes

Líderes: 61 respostas, sendo 46 da FINX (T1 = 15, T2 = 16, T3 = 15) e 15 da Xforce (T1 = 6, T2 = 6, T3 = 3). As respostas não podem ser pareadas entre as ondas, porque não há identificação do respondente. As coletas foram em dez/2025–jan/2026 (T1), jun/2026 (T2) e ago/2026 (T3).

Os principais resultados indicam:
- FINX: a percepção de pressão constante por resultados aumentou de T2 para T3 (W = 27.5; p < 0.001). A concordância foi de 3/16 (19%) para 11/15 (73%). A redação do item no T2 é diferente.
- Xforce: a necessidade de intervir em conflitos diminuiu de T1 para T2 (W = 32.0; p = 0.023). A discordância foi de 1/6 para 5/6.
- Nos demais itens não houve diferença significativa entre as ondas (p ≥ 0.05).

In [2]:
tabela("lideres")

    Item
1   5. percebo pressao constante para entrega de resultados que exigem alto nivel de desempenho.
2
3
4
5
6   7. preciso intervir frequentemente em conflitos que desgastam minha rotina de trabalho.
7
8
9
10
11  4. trabalho alem do horario previsto devido as demandas da lideranca (ex.: responder mensagens fora do expediente, reunioes extras).
12
13
14
15
16  8. sinto que minha equipe depende excessivamente de mim para resolver problemas simples (ex.: duvidas recorrentes que poderiam ser resolvidas sem supervisao direta).
17
18
19
20
21  20. sinto-me preparado(a) para lidar com situacoes de sofrimento emocional, saude mental ou crise envolvendo membros da equipe (ex.: ansiedade, burnout, conflitos pessoais afetando o trabalho). (invertida)
22
23
24
25
26  18. sou exposto(a) com frequencia a reclamacoes, criticas ou conflitos emocionais relacionados a lideranca (ex.: clientes insatisfeitos, pressao de superiores ou equipe).
27
28
29
30
31  15. tenho autonomia para contratar colaboradores quando identifico essa necessidade.
32
33
34
35
36  16. tenho autonomia para desligar colaboradores quando isso se faz necessario (seguindo politicas internas e processos formais.
37
38
39
40
41  2. tenho suporte adequado = (recursos/informacao) para tomar decisoes de forma segura.
42
43
44
45
46  9. estou satisfeito(a) com a performance geral da minha equipe.
47
48
49
50
51  14. recebo feedback e apoio da alta direcao quando necessario. (invertida)
52
53
54
55
56  19. meu trabalho exige constante tomada de decisoes que afetam a seguranca, bem-estar ou desempenho de outras pessoas (ex.: realocar pessoas, dar feedback dificil, definir prioridades).
57
58
59
60
61  1. sinto que a carga de responsabilidade pelas decisoes e elevada.
62
63
64
65
66  12. a falta de preparo tecnico ou comportamental da equipe aumenta meu nivel de estresse.
67
68
69
70
71  13. tenho autonomia suficiente para organizar o trabalho da minha equipe (ex.: definir prazos, distribuir tarefas). (invertida)
72
73
74
75
76  6. sinto-me preparado(a) e confiante para lidar com conflitos internos.
77
78
79
80
81  11. minha equipe possui competencias comportamentais adequadas as demandas de trabalho (ex.: comunicacao, responsabilidade, colaboracao). (invertida)
82
83
84
85
86  3. ha clareza sobre minhas responsabilidades e limites de autoridade (ex.: sei ate onde posso decidir sozinho e quando preciso escalonar). (invertida)
87
88
89
90
91  17. as politicas internas da empresa permitem decisoes de gestao de pessoas com agilidade
92
93
94
95
96  10. minha equipe possui conhecimentos tecnicos adequados para exercer suas funcoes (ex.: dominio de ferramentas, processos, habilidades operacionais). (invertida)
97
98
99
100
101 21. o nivel de autonomia e o apoio que recebe da organizacao impacta negativamente minha saude mental e emocional.
102
103
104
105
106 22. o nivel de exposicao emocional que sou exposto atualmente, impacta minha saude mental e emocional.
107
108
109
110
111 23. em qual setor/departamento voce trabalha?
112
113
114
115
116
117
118
119 24. ha quanto tempo voce trabalha na empresa?
120
121
122
123
124
125 25. marque as jornadas que voce participou:
126
127
128
129
130
131
132
133
134
135
136
137
138
    Resposta
1   (1) discordo totalmente
2   (2) discordo parcialmente
3   (3) nem concordo nem discordo
4   (4) concordo parcialmente
5   (5) concordo totalmente
6   (1) discordo totalmente
7   (2) discordo parcialmente
8   (3) nem concordo nem discordo
9   (4) concordo parcialmente
10  (5) concordo totalmente
11  (1) discordo totalmente
12  (2) discordo parcialmente
13  (3) nem concordo nem discordo
14  (4) concordo parcialmente
15  (5) concordo totalmente
16  (1) discordo totalmente
17  (2) discordo parcialmente
18  (3) nem concordo nem discordo
19  (4) concordo parcialmente
20  (5) concordo totalmente
21  (1) discordo totalmente
22  (2) discordo parcialmente
23  (3) nem concordo nem discordo
24  (4) concordo parcialmente
25  (5) concordo totalmente
26  (1) discordo totalmente
27  (2) discordo parcialmente
28  (3) nem concordo nem discordo
29  (4) concordo parcialmente
30  (5) concordo totalmente
31  (1) discordo totalmente
32  (2) discordo parcialmente
33  (3) nem concordo nem discordo
34  (4) concordo parcialmente
35  (5) concordo totalmente
36  (1) discordo totalmente
37  (2) discordo parcialmente
38  (3) nem concordo nem discordo
39  (4) concordo parcialmente
40  (5) concordo totalmente
41  (1) discordo totalmente
42  (2) discordo parcialmente
43  (3) nem concordo nem discordo
44  (4) concordo parcialmente
45  (5) concordo totalmente
46  (1) discordo totalmente
47  (2) discordo parcialmente
48  (3) nem concordo nem discordo
49  (4) concordo parcialmente
50  (5) concordo totalmente
51  (1) discordo totalmente
52  (2) discordo parcialmente
53  (3) nem concordo nem discordo
54  (4) concordo parcialmente
55  (5) concordo totalmente
56  (1) discordo totalmente
57  (2) discordo parcialmente
58  (3) nem concordo nem discordo
59  (4) concordo parcialmente
60  (5) concordo totalmente
61  (1) discordo totalmente
62  (2) discordo parcialmente
63  (3) nem concordo nem discordo
64  (4) concordo parcialmente
65  (5) concordo totalmente
66  (1) discordo totalmente
67  (2) discordo parcialmente
68  (3) nem concordo nem discordo
69  (4) concordo parcialmente
70  (5) concordo totalmente
71  (1) discordo totalmente
72  (2) discordo parcialmente
73  (3) nem concordo nem discordo
74  (4) concordo parcialmente
75  (5) concordo totalmente
76  (1) discordo totalmente
77  (2) discordo parcialmente
78  (3) nem concordo nem discordo
79  (4) concordo parcialmente
80  (5) concordo totalmente
81  (1) discordo totalmente
82  (2) discordo parcialmente
83  (3) nem concordo nem discordo
84  (4) concordo parcialmente
85  (5) concordo totalmente
86  (1) discordo totalmente
87  (2) discordo parcialmente
88  (3) nem concordo nem discordo
89  (4) concordo parcialmente
90  (5) concordo totalmente
91  (1) discordo totalmente
92  (2) discordo parcialmente
93  (3) nem concordo nem discordo
94  (4) concordo parcialmente
95  (5) concordo totalmente
96  (1) discordo totalmente
97  (2) discordo parcialmente
98  (3) nem concordo nem discordo
99  (4) concordo parcialmente
100 (5) concordo totalmente
101 (1) discordo totalmente
102 (2) discordo parcialmente
103 (3) nem concordo nem discordo
104 (4) concordo parcialmente
105 (5) concordo totalmente
106 (1) discordo totalmente
107 (2) discordo parcialmente
108 (3) nem concordo nem discordo
109 (4) concordo parcialmente
110 (5) concordo totalmente
111 (1) administrativo
112 (2) comercial/vendas
113 (3) financeiro
114 (4) recursos humanos
115 (5) operacional/producao
116 (6) marketing
117 (7) tecnologia/informatica
118 (8) outro (especifique)
119 (1) menos de 3 meses
120 (2) de 3 a 6 meses
121 (3) de 6 meses a 1 ano
122 (4) de 1 a 3 anos
123 (5) de 3 a 5 anos
124 (6) mais de 5 anos
125 (1) a mente "mente"
126 (2) mudar a era do apontamento de falhas para a era da celebracao dos acertos
127 (3) contemplar o belo
128 (4) de sempre uma nova chance para si mesmo
129 (5) expor e nao impor ideias
130 (6) pensar antes de agir e reagir
131 (7) ninguem da o que nao tem
132 (8) circuito fechado da memoria
133 (9) tecnica do d.c.d.
134 (10) armadilhas da mente
135 (11) o caminho mudou - armadilha do conformismo
136 (12) armadilha da catastrofizacao
137 (13) armadilha da comparacao
138 (14) armadilha do medo de errar e do excesso de confianca
    finx_T1 finx_T1→T2           finx_T2 finx_T2→T3           finx_T3 xforce_T1
1   2       W = 164.5; p = 0.073 6       W = 27.5; p < 0.001  0       1
2   3                            4                            1       0
3   4                            3                            3       1
4   5                            3                            4       3
5   1                            0                            7       1
6   6       W = 106.5; p = 0.587 7       W = 93.0; p = 0.276  3       0
7   6                            3                            3       1
8   3                            3                            7       4
9   0                            3                            1       1
10  0                            0                            1       0
11  3       W = 136.5; p = 0.515 6       W = 72.5; p = 0.057  1       3
12  5                            2                            4       0
13  1                            3                            1       1
14  4                            4                            5       1
15  2                            1                            4       1
16  4       W = 75.0; p = 0.085  2       W = 120.5; p = 1.000 3       0
17  9                            9                            7       2
18  1                            3                            2       2
19  0                            2                            2       1
20  0                            0                            1       1
21  1       W = 96.0; p = 0.819  3       W = 108.0; p = 0.908 1       0
22  2                            5                            3       0
23  1                            3                            1       1
24  6                            3                            8       4
25  3                            0                            2       1
26  9       W = 81.0; p = 0.580  9       W = 68.5; p = 0.094  4       1
27  3                            1                            5       0
28  1                            4                            4       1
29  0                            0                            1       3
30  0                            0                            1       0
31  1       W = 58.5; p = 0.184  1       W = 131.0; p = 0.253 3       2
32  5                            2                            1       2
33  3                            3                            5       1
34  0                            3                            4       1
35  3                            5                            2       0
36  0       W = 112.0; p = 0.132 1       W = 82.5; p = 0.312  1       2
37  0                            2                            0       1
38  2                            3                            2       0
39  3                            3                            5       1
40  7                            5                            7       2
41  0       W = 127.5; p = 0.766 0       W = 128.0; p = 0.752 1       0
42  2                            2                            1       1
43  2                            2                            1       1
44  3                            5                            7       3
45  8                            7                            5       1
46  1       W = 117.5; p = 0.826 0       W = 101.5; p = 0.448 0       1
47  2                            3                            2       2
48  1                            1                            1       0
49  4                            7                            5       3
50  6                            5                            7       0
51  1       W = 81.5; p = 0.652  1       W = 112.5; p = 0.753 2       0
52  2                            3                            1       1
53  3                            1                            5       1
54  4                            4                            2       1
55  3                            5                            5       3
56  2       W = 107.0; p = 0.441 5       W = 77.5; p = 0.226  3       0
57  4                            1                            2       1
58  2                            5                            3       1
59  3                            2                            4       2
60  2                            1                            3       2
61  3       W = 90.5; p = 0.237  4       W = 94.5; p = 0.305  2       1
62  5                            0                            2       1
63  5                            5                            3       2
64  0                            7                            4       2
65  2                            0                            4       0
66  3       W = 102.0; p = 0.595 5       W = 89.0; p = 0.483  4       2
67  5                            4                            4       0
68  3                            4                            4       0
69  1                            0                            3       3
70  1                            1                            0       1
71  0       W = 89.5; p = 0.952  0       W = 127.0; p = 0.277 1       0
72  0                            1                            2       1
73  1                            0                            0       2
74  3                            3                            4       1
75  9                            10                           8       2
76  0       W = 102.0; p = 0.413 11      W = 130.5; p = 0.634 0       0
77  1                            5                            0       0
78  2                            0                            0       0
79  3                            0                            6       3
80  9                            0                            9       3
81  0       W = 121.5; p = 0.425 0       W = 139.0; p = 0.427 1       0
82  0                            3                            1       2
83  1                            2                            1       0
84  7                            5                            11      3
85  5                            6                            1       1
86  0       W = 103.5; p = 0.493 0       W = 122.0; p = 0.948 0       0
87  2                            2                            1       1
88  1                            1                            2       0
89  6                            4                            4       3
90  6                            9                            8       2
91  0       W = 83.5; p = 0.719  0       W = 104.5; p = 1.000 0       0
92  0                            1                            1       2
93  4                            3                            4       1
94  6                            5                            4       1
95  3                            5                            6       2
96  0       —                    —       —                    0       0
97  1                            —                            1       3
98  1                            —                            1       0
99  6                            —                            7       2
100 6                            —                            6       1
101 —       —                    10      —                    —       —
102 —                            0                            —       —
103 —                            2                            —       —
104 —                            2                            —       —
105 —                            0                            —       —
106 —       —                    6       —                    —       —
107 —                            2                            —       —
108 —                            2                            —       —
109 —                            3                            —       —
110 —                            1                            —       —
111 —       —                    —       —                    3       —
112 —                            —                            6       —
113 —                            —                            0       —
114 —                            —                            1       —
115 —                            —                            2       —
116 —                            —                            1       —
117 —                            —                            0       —
118 —                            —                            2       —
119 —       —                    —       —                    0       —
120 —                            —                            3       —
121 —                            —                            3       —
122 —                            —                            6       —
123 —                            —                            1       —
124 —                            —                            2       —
125 —       —                    —       —                    11      —
126 —                            —                            9       —
127 —                            —                            13      —
128 —                            —                            11      —
129 —                            —                            9       —
130 —                            —                            10      —
131 —                            —                            7       —
132 —                            —                            9       —
133 —                            —                            9       —
134 —                            —                            11      —
135 —                            —                            8       —
136 —                            —                            8       —
137 —                            —                            9       —
138 —                            —                            8       —
    xforce_T1→T2        xforce_T2 xforce_T2→T3        xforce_T3
1   W = 28.5; p = 0.096 3         W = 3.5; p = 0.179  0
2                       1                             1
3                       1                             0
4                       1                             2
5                       0                             0
6   W = 32.0; p = 0.023 3         W = 6.5; p = 0.583  1
7                       2                             1
8                       1                             0
9                       0                             1
10                      0                             0
11  W = 23.0; p = 0.418 4         W = 6.0; p = 0.477  1
12                      0                             1
13                      2                             0
14                      0                             1
15                      0                             0
16  W = 23.5; p = 0.410 2         W = 11.0; p = 0.684 2
17                      1                             0
18                      2                             0
19                      0                             1
20                      1                             0
21  W = 8.0; p = 0.091  4         W = 15.0; p = 0.101 0
22                      2                             0
23                      0                             0
24                      0                             3
25                      0                             0
26  W = 22.0; p = 0.209 4         W = 9.0; p = 1.000  2
27                      1                             0
28                      0                             0
29                      0                             1
30                      1                             0
31  W = 8.0; p = 0.117  1         W = 11.5; p = 0.583 0
32                      0                             0
33                      1                             2
34                      3                             1
35                      1                             0
36  W = 16.5; p = 0.869 1         W = 10.0; p = 0.895 0
37                      0                             1
38                      1                             1
39                      3                             0
40                      1                             1
41  W = 20.0; p = 0.788 0         W = 4.0; p = 0.167  0
42                      1                             0
43                      1                             0
44                      4                             2

## §2 Table 2 - Inventário de Saúde Emocional

Saúde Emocional: 216 respostas, sendo 172 da FINX (T1 = 86, T2 = 86) e 44 da Xforce (T1 = 25, T2 = 19). As respostas não podem ser pareadas entre as ondas, porque não há identificação do respondente. As coletas foram em dez/2025–jan/2026 (T1) e abr/2026 (T2).

Os principais resultados indicam:
- FINX: a liberdade para organizar as próprias atividades diminuiu de T1 para T2 (W = 4596.0; p < 0.001). "Muitas vezes" e "sempre" passaram de 91% para 73%.
- FINX: o encorajamento para usar criatividade e conhecimento diminuiu de T1 para T2 (W = 4342.0; p = 0.015). "Muitas vezes" e "sempre" passaram de 80% para 73%.
- Xforce: nenhum item teve diferença significativa entre T1 e T2 (p ≥ 0.05).

In [3]:
tabela("emocional")

    Item
1   34. tem liberdade para organizar suas atividades? (ex.: escolher a ordem das tarefas)
2
3
4
5
6   35. e encorajado(a) a usar criatividade e conhecimento? (ex.: sugerir melhorias ou novas ideias)
7
8
9
10
11  4. cobra demais de si mesmo(a)? (ex.: sentir que nunca fez o suficiente)
12
13
14
15
16  31. sente-se satisfeito(a) consigo e com suas escolhas? (ex.: acreditar que esta seguindo o caminho certo)
17
18
19
20
21  1. consegue lidar bem com frustracoes e imprevistos? (ex.: manter a calma mesmo quando nao cumpre um prazo)
22
23
24
25
26  21. anda esquecido(a) ou com deficit de memoria? (ex.: esquecer compromissos ou nomes)
27
28
29
30
31  37. sente-se pertencente a equipe e a empresa? (ex.: sentir-se parte do grupo)
32
33
34
35
36  15. tem dores de cabeca ou dores musculares?
37
38
39
40
41  17. tem dificuldas para dormir?
42
43
44
45
46  45. recebe feedback para melhorar seu desempenho? (ex.: orientacoes claras e uteis)
47
48
49
50
51  16. costuma sentir-se cansado(a)? (ex.: acordar sem energia mesmo apos dormir)
52
53
54
55
56  44. sente-se a vontade para falar com sua lideranca? (ex.: expressar expectativas e conflitos sem medo)
57
58
59
60
61  47. sua lideranca demonstra preocupacao com seu bem-estar? (ex.: perguntar como voce esta e oferecer apoio)
62
63
64
65
66  26. costuma sentir ansiedade ou angustia? (ex.: sentir aperto no peito sem motivo claro)
67
68
69
70
71  32. esta satisfeito(a) com sua funcao atual? (ex.: sentir que exerce um papel adequado a voce)
72
73
74
75
76  27. tem queda de cabelo sem causa aparente?
77
78
79
80
81  48. sente-se valorizado(a) na empresa? (ex.: reconhecimento pelos resultados)
82
83
84
85
86  33. a empresa confia em sua capacidade de decisao? (ex.: resolver problemas sem pedir autorizacao para tudo)
87
88
89
90
91  2. mantem o autocontrole em situacoes de estresse ou conflito? (ex.: nao perder a cabeca em discussoes)
92
93
94
95
96  25. tem falta ou excesso de apetite? (ex.: assaltar a geladeira a noite ou pular refeicoes)
97
98
99
100
101 30. tem vontade de desistir de viver? (ex.: pensamentos sobre morte ou nao continuar)
102
103
104
105
106 3. consegue ser assertivo sem elevar o tom de voz ou ser agressivo? (ex.: falar o que precisa sem gritar)
107
108
109
110
111 41. este e um lugar psicologicamente saudavel? (ex.: trabalhar sem medo constante ou tensao excessiva)
112
113
114
115
116 6. sofre por antecipacao? (ex.: preocupar-se com algo que ainda nem aconteceu)
117
118
119
120
121 28. tem pensamentos perturbadores? (ex.: imaginar cenarios negativos ou pensamentos angustiantes)
122
123
124
125
126 24. percebe diminuicao da libido? (ex.: perda de interesse sexual)
127
128
129
130
131 22. tem dores de estomago ou problemas intestinais?
132
133
134
135
136 10. considera-se timido(a) ou inseguro(a)?
137
138
139
140
141 49. tem orgulho em trabalhar nesta empresa? (ex.: falar bem do local para outras pessoas)
142
143
144
145
146 36. os colaboradores se respeitam e se preocupam uns com os outros? (ex.: ausencia de humilhacao ou competicao toxica)
147
148
149
150
151 23. tem sentimentos de inferioridade? (ex.: acreditar que nao e bom o bastante)
152
153
154
155
156 38. existe senso de equipe? (ex.: colaboracao entre os profissionais)
157
158
159
160
161 7. remoi situacoes do passado? (ex.: lembrar com frequencia de magoas antigas)
162
163
164
165
166 39. ja sofreu assedio nesta empresa? (ex.: gritos, piadas, humilhacoes ou bullying)
167
168
169
170
171 9. sente algum tipo de fobia social? (ex.: medo de falar em publico)
172
173
174
175
176 18. sente-se desmotivado(a) ou desanimado(a)? (ex.: sem vontade de iniciar tarefas simples)
177
178
179
180
181 19. percebe-se triste ou com humor depressivo? (ex.: falta de prazer nas atividades diarias)
182
183
184
185
186 42. todos sao bem tratados independentemente de diferencas pessoais? (ex.: ausencia de preconceito por idade, genero ou etnia)
187
188
189
190
191 20. costuma ter dificuldade de concentracao? (ex.: iniciar tarefas e nao concluir)
192
193
194
195
196 46. recebe treinamentos adequados? (ex.: aprender o necessario para cumprir suas funcoes)
197
198
199
200
201 29. tem chorado mais ultimamente? (ex.: chorar por situacoes pequenas)
202
203
204
205
206 40. os colaboradores possuem as mesmas oportunidades? (ex.: promocoes sem favoritismo)
207
208
209
210
211 43. tem acesso aos equipamentoe e materiais adequados para desempenhar suas tarefas?
212
213
214
215
216 5. cobra demais dos outros? (ex.: esperar que as pessoas ajam como voce)
217
218
219
220
221 8. valoriza excessivamente a opiniao dos outros?
222
223
224
225
226 11. tem dificuldade em conviver com pessoas mais lentas? (ex.: ficar irritado quando alguem demora para entender algo)
227
228
229
230
231 12. ja se automutilou? (ex.: se machucar fisicamente para aliviar dor emocional)
232
233
234
235
236 13. sofre por padroes de beleza ou sucesso? (ex.: sentir-se inadequado por sua aparencia ou carreira)
237
238
239
240
241 14. sente-se intoxicado digitalmente? (ex.: passar muitas horas no celular)
242
243
244
245
246 50. o nivel de autonomia que possui atualmente na empresa, afeta negativamente sua saude emocional/mental?
247
248
249
250
251 51. o nivel de relacionamento e cooperacao entre colaboradores e equipes afeta negativamente sua saude emocional/mental?
252
253
254
255
256 52. o clima organizacional da empresa impacta negativamente sua saude emocional/mental?
257
258
259
260
261 53. a atuacao de sua lideranca tem impactado negativamente sua saude emocional/mental?
262
263
264
265
266 54. consegue separar suas atividades profissionais com sua vida pessoal?
267
268
269
270
271 55. o que mais lhe atrai em trabalhar nesta empresa? (pode assinalar mais de uma alternativa)
272
273
274
275
276 56. acha importante que sua empresa invista em um programa de prevencao de transtornos emocionais?
277
278 57. ha quanto esta atuando nessa empresa?
279
280
281
282
283
284 58. setor de atuacao:
285
286
287
288 59. assinale quais foram as jornadas de ouro quinzenal que voce participou:
289
290
291
292
293
294
295
296
297
    Resposta                                                            finx_T1
1   (1) nunca                                                           0
2   (2) raramente                                                       3
3   (3) as vezes                                                        5
4   (4) muitas vezes                                                    40
5   (5) sempre                                                          38
6   (1) nunca                                                           1
7   (2) raramente                                                       5
8   (3) as vezes                                                        11
9   (4) muitas vezes                                                    30
10  (5) sempre                                                          39
11  (1) nunca                                                           0
12  (2) raramente                                                       3
13  (3) as vezes                                                        14
14  (4) muitas vezes                                                    26
15  (5) sempre                                                          43
16  (1) nunca                                                           1
17  (2) raramente                                                       6
18  (3) as vezes                                                        28
19  (4) muitas vezes                                                    37
20  (5) sempre                                                          14
21  (1) nunca                                                           0
22  (2) raramente                                                       12
23  (3) as vezes                                                        28
24  (4) muitas vezes                                                    39
25  (5) sempre                                                          7
26  (1) nunca                                                           8
27  (2) raramente                                                       18
28  (3) as vezes                                                        32
29  (4) muitas vezes                                                    17
30  (5) sempre                                                          10
31  (1) nunca                                                           0
32  (2) raramente                                                       1
33  (3) as vezes                                                        9
34  (4) muitas vezes                                                    34
35  (5) sempre                                                          42
36  (1) nunca                                                           4
37  (2) raramente                                                       22
38  (3) as vezes                                                        19
39  (4) muitas vezes                                                    23
40  (5) sempre                                                          17
41  (1) nunca                                                           13
42  (2) raramente                                                       24
43  (3) as vezes                                                        24
44  (4) muitas vezes                                                    17
45  (5) sempre                                                          8
46  (1) nunca                                                           3
47  (2) raramente                                                       5
48  (3) as vezes                                                        12
49  (4) muitas vezes                                                    23
50  (5) sempre                                                          43
51  (1) nunca                                                           4
52  (2) raramente                                                       11
53  (3) as vezes                                                        21
54  (4) muitas vezes                                                    34
55  (5) sempre                                                          16
56  (1) nunca                                                           1
57  (2) raramente                                                       3
58  (3) as vezes                                                        11
59  (4) muitas vezes                                                    28
60  (5) sempre                                                          43
61  (1) nunca                                                           4
62  (2) raramente                                                       7
63  (3) as vezes                                                        14
64  (4) muitas vezes                                                    15
65  (5) sempre                                                          46
66  (1) nunca                                                           11
67  (2) raramente                                                       17
68  (3) as vezes                                                        19
69  (4) muitas vezes                                                    24
70  (5) sempre                                                          15
71  (1) nunca                                                           1
72  (2) raramente                                                       5
73  (3) as vezes                                                        18
74  (4) muitas vezes                                                    37
75  (5) sempre                                                          25
76  (1) nunca                                                           28
77  (2) raramente                                                       12
78  (3) as vezes                                                        19
79  (4) muitas vezes                                                    12
80  (5) sempre                                                          15
81  (1) nunca                                                           3
82  (2) raramente                                                       10
83  (3) as vezes                                                        16
84  (4) muitas vezes                                                    34
85  (5) sempre                                                          23
86  (1) nunca                                                           2
87  (2) raramente                                                       6
88  (3) as vezes                                                        19
89  (4) muitas vezes                                                    44
90  (5) sempre                                                          15
91  (1) nunca                                                           0
92  (2) raramente                                                       3
93  (3) as vezes                                                        23
94  (4) muitas vezes                                                    41
95  (5) sempre                                                          19
96  (1) nunca                                                           13
97  (2) raramente                                                       16
98  (3) as vezes                                                        19
99  (4) muitas vezes                                                    25
100 (5) sempre                                                          13
101 (1) nunca                                                           52
102 (2) raramente                                                       13
103 (3) as vezes                                                        13
104 (4) muitas vezes                                                    2
105 (5) sempre                                                          6
106 (1) nunca                                                           1
107 (2) raramente                                                       2
108 (3) as vezes                                                        11
109 (4) muitas vezes                                                    47
110 (5) sempre                                                          25
111 (1) nunca                                                           3
112 (2) raramente                                                       15
113 (3) as vezes                                                        24
114 (4) muitas vezes                                                    32
115 (5) sempre                                                          12
116 (1) nunca                                                           2
117 (2) raramente                                                       9
118 (3) as vezes                                                        18
119 (4) muitas vezes                                                    28
120 (5) sempre                                                          29
121 (1) nunca                                                           23
122 (2) raramente                                                       19
123 (3) as vezes                                                        16
124 (4) muitas vezes                                                    15
125 (5) sempre                                                          13
126 (1) nunca                                                           21
127 (2) raramente                                                       20
128 (3) as vezes                                                        26
129 (4) muitas vezes                                                    16
130 (5) sempre                                                          3
131 (1) nunca                                                           21
132 (2) raramente                                                       31
133 (3) as vezes                                                        20
134 (4) muitas vezes                                                    10
135 (5) sempre                                                          4
136 (1) nunca                                                           18
137 (2) raramente                                                       25
138 (3) as vezes                                                        21
139 (4) muitas vezes                                                    15
140 (5) sempre                                                          7
141 (1) nunca                                                           1
142 (2) raramente                                                       3
143 (3) as vezes                                                        9
144 (4) muitas vezes                                                    27
145 (5) sempre                                                          46
146 (1) nunca                                                           0
147 (2) raramente                                                       4
148 (3) as vezes                                                        11
149 (4) muitas vezes                                                    33
150 (5) sempre                                                          37
151 (1) nunca                                                           18
152 (2) raramente                                                       18
153 (3) as vezes                                                        24
154 (4) muitas vezes                                                    16
155 (5) sempre                                                          10
156 (1) nunca                                                           0
157 (2) raramente                                                       1
158 (3) as vezes                                                        12
159 (4) muitas vezes                                                    33
160 (5) sempre                                                          40
161 (1) nunca                                                           6
162 (2) raramente                                                       24
163 (3) as vezes                                                        24
164 (4) muitas vezes                                                    19
165 (5) sempre                                                          13
166 (1) nunca                                                           64
167 (2) raramente                                                       13
168 (3) as vezes                                                        3
169 (4) muitas vezes                                                    6
170 (5) sempre                                                          0
171 (1) nunca                                                           27
172 (2) raramente                                                       20
173 (3) as vezes                                                        17
174 (4) muitas vezes                                                    13
175 (5) sempre                                                          9
176 (1) nunca                                                           9
177 (2) raramente                                                       25
178 (3) as vezes                                                        34
179 (4) muitas vezes                                                    14
180 (5) sempre                                                          4
181 (1) nunca                                                           15
182 (2) raramente                                                       29
183 (3) as vezes                                                        22
184 (4) muitas vezes                                                    15
185 (5) sempre                                                          5

## §3 Table 3 - Inventário de Saúde Mental exclusivo para Líderes (3 categorias)

Líderes: 61 respostas, sendo 46 da FINX (T1 = 15, T2 = 16, T3 = 15) e 15 da Xforce (T1 = 6, T2 = 6, T3 = 3). As respostas não podem ser pareadas entre as ondas, porque não há identificação do respondente. As coletas foram em dez/2025–jan/2026 (T1), jun/2026 (T2) e ago/2026 (T3).

Os principais resultados indicam:
- FINX: a percepção de pressão constante por resultados aumentou de T2 para T3 (W = 27.5; p < 0.001). "Concordo" foi de 3/16 (19%) para 11/15 (73%). A redação do item no T2 é diferente.
- Xforce: a necessidade de intervir em conflitos diminuiu de T1 para T2 (W = 32.0; p = 0.023). "Discordo" foi de 1/6 para 5/6.
- Nos demais itens não houve diferença significativa entre as ondas (p ≥ 0.05).

(risco) = item de risco: maior concordância/frequência indica maior risco.

In [4]:
tabela("lideres", agrupar = TRUE)

   Item
1  5. percebo pressao constante para entrega de resultados que exigem alto nivel de desempenho. (risco)
2
3
4  7. preciso intervir frequentemente em conflitos que desgastam minha rotina de trabalho. (risco)
5
6
7  4. trabalho alem do horario previsto devido as demandas da lideranca (ex.: responder mensagens fora do expediente, reunioes extras). (risco)
8
9
10 8. sinto que minha equipe depende excessivamente de mim para resolver problemas simples (ex.: duvidas recorrentes que poderiam ser resolvidas sem supervisao direta). (risco)
11
12
13 20. sinto-me preparado(a) para lidar com situacoes de sofrimento emocional, saude mental ou crise envolvendo membros da equipe (ex.: ansiedade, burnout, conflitos pessoais afetando o trabalho).
14
15
16 18. sou exposto(a) com frequencia a reclamacoes, criticas ou conflitos emocionais relacionados a lideranca (ex.: clientes insatisfeitos, pressao de superiores ou equipe). (risco)
17
18
19 15. tenho autonomia para contratar colaboradores quando identifico essa necessidade.
20
21
22 16. tenho autonomia para desligar colaboradores quando isso se faz necessario (seguindo politicas internas e processos formais.
23
24
25 2. tenho suporte adequado = (recursos/informacao) para tomar decisoes de forma segura.
26
27
28 9. estou satisfeito(a) com a performance geral da minha equipe.
29
30
31 14. recebo feedback e apoio da alta direcao quando necessario.
32
33
34 19. meu trabalho exige constante tomada de decisoes que afetam a seguranca, bem-estar ou desempenho de outras pessoas (ex.: realocar pessoas, dar feedback dificil, definir prioridades). (risco)
35
36
37 1. sinto que a carga de responsabilidade pelas decisoes e elevada. (risco)
38
39
40 12. a falta de preparo tecnico ou comportamental da equipe aumenta meu nivel de estresse. (risco)
41
42
43 13. tenho autonomia suficiente para organizar o trabalho da minha equipe (ex.: definir prazos, distribuir tarefas).
44
45
46 6. sinto-me preparado(a) e confiante para lidar com conflitos internos.
47
48
49 11. minha equipe possui competencias comportamentais adequadas as demandas de trabalho (ex.: comunicacao, responsabilidade, colaboracao).
50
51
52 3. ha clareza sobre minhas responsabilidades e limites de autoridade (ex.: sei ate onde posso decidir sozinho e quando preciso escalonar).
53
54
55 17. as politicas internas da empresa permitem decisoes de gestao de pessoas com agilidade
56
57
58 10. minha equipe possui conhecimentos tecnicos adequados para exercer suas funcoes (ex.: dominio de ferramentas, processos, habilidades operacionais).
59
60
61 21. o nivel de autonomia e o apoio que recebe da organizacao impacta negativamente minha saude mental e emocional. (risco)
62
63
64 22. o nivel de exposicao emocional que sou exposto atualmente, impacta minha saude mental e emocional. (risco)
65
66
67 23. em qual setor/departamento voce trabalha?
68
69
70
71
72
73
74
75 24. ha quanto tempo voce trabalha na empresa?
76
77
78
79
80
81 25. marque as jornadas que voce participou:
82
83
84
85
86
87
88
89
90
91
92
93
94
   Resposta
1  (1) discordo
2  (2) neutro
3  (3) concordo
4  (1) discordo
5  (2) neutro
6  (3) concordo
7  (1) discordo
8  (2) neutro
9  (3) concordo
10 (1) discordo
11 (2) neutro
12 (3) concordo
13 (1) discordo
14 (2) neutro
15 (3) concordo
16 (1) discordo
17 (2) neutro
18 (3) concordo
19 (1) discordo
20 (2) neutro
21 (3) concordo
22 (1) discordo
23 (2) neutro
24 (3) concordo
25 (1) discordo
26 (2) neutro
27 (3) concordo
28 (1) discordo
29 (2) neutro
30 (3) concordo
31 (1) discordo
32 (2) neutro
33 (3) concordo
34 (1) discordo
35 (2) neutro
36 (3) concordo
37 (1) discordo
38 (2) neutro
39 (3) concordo
40 (1) discordo
41 (2) neutro
42 (3) concordo
43 (1) discordo
44 (2) neutro
45 (3) concordo
46 (1) discordo
47 (2) neutro
48 (3) concordo
49 (1) discordo
50 (2) neutro
51 (3) concordo
52 (1) discordo
53 (2) neutro
54 (3) concordo
55 (1) discordo
56 (2) neutro
57 (3) concordo
58 (1) discordo
59 (2) neutro
60 (3) concordo
61 (1) discordo
62 (2) neutro
63 (3) concordo
64 (1) discordo
65 (2) neutro
66 (3) concordo
67 (1) administrativo
68 (2) comercial/vendas
69 (3) financeiro
70 (4) recursos humanos
71 (5) operacional/producao
72 (6) marketing
73 (7) tecnologia/informatica
74 (8) outro (especifique)
75 (1) menos de 3 meses
76 (2) de 3 a 6 meses
77 (3) de 6 meses a 1 ano
78 (4) de 1 a 3 anos
79 (5) de 3 a 5 anos
80 (6) mais de 5 anos
81 (1) a mente "mente"
82 (2) mudar a era do apontamento de falhas para a era da celebracao dos acertos
83 (3) contemplar o belo
84 (4) de sempre uma nova chance para si mesmo
85 (5) expor e nao impor ideias
86 (6) pensar antes de agir e reagir
87 (7) ninguem da o que nao tem
88 (8) circuito fechado da memoria
89 (9) tecnica do d.c.d.
90 (10) armadilhas da mente
91 (11) o caminho mudou - armadilha do conformismo
92 (12) armadilha da catastrofizacao
93 (13) armadilha da comparacao
94 (14) armadilha do medo de errar e do excesso de confianca
   finx_T1 finx_T1→T2           finx_T2 finx_T2→T3           finx_T3 xforce_T1
1  5       W = 164.5; p = 0.073 10      W = 27.5; p < 0.001  1       1
2  4                            3                            3       1
3  6                            3                            11      4
4  12      W = 106.5; p = 0.587 10      W = 93.0; p = 0.276  6       1
5  3                            3                            7       4
6  0                            3                            2       1
7  8       W = 136.5; p = 0.515 8       W = 72.5; p = 0.057  5       3
8  1                            3                            1       1
9  6                            5                            9       2
10 13      W = 75.0; p = 0.085  11      W = 120.5; p = 1.000 10      2
11 1                            3                            2       2
12 0                            2                            3       2
13 3       W = 96.0; p = 0.819  8       W = 108.0; p = 0.908 4       0
14 1                            3                            1       1
15 9                            3                            10      5
16 12      W = 81.0; p = 0.580  10      W = 68.5; p = 0.094  9       1
17 1                            4                            4       1
18 0                            0                            2       3
19 6       W = 58.5; p = 0.184  3       W = 131.0; p = 0.253 4       4
20 3                            3                            5       1
21 3                            8                            6       1
22 0       W = 112.0; p = 0.132 3       W = 82.5; p = 0.312  1       3
23 2                            3                            2       0
24 10                           8                            12      3
25 2       W = 127.5; p = 0.766 2       W = 128.0; p = 0.752 2       1
26 2                            2                            1       1
27 11                           12                           12      4
28 3       W = 117.5; p = 0.826 3       W = 101.5; p = 0.448 2       3
29 1                            1                            1       0
30 10                           12                           12      3
31 3       W = 81.5; p = 0.652  4       W = 112.5; p = 0.753 3       1
32 3                            1                            5       1
33 7                            9                            7       4
34 6       W = 107.0; p = 0.441 6       W = 77.5; p = 0.226  5       1
35 2                            5                            3       1
36 5                            3                            7       4
37 8       W = 90.5; p = 0.237  4       W = 94.5; p = 0.305  4       2
38 5                            5                            3       2
39 2                            7                            8       2
40 8       W = 102.0; p = 0.595 9       W = 89.0; p = 0.483  8       2
41 3                            4                            4       0
42 2                            1                            3       4
43 0       W = 89.5; p = 0.952  1       W = 127.0; p = 0.277 3       1
44 1                            0                            0       2
45 12                           13                           12      3
46 1       W = 102.0; p = 0.413 16      W = 130.5; p = 0.634 0       0
47 2                            0                            0       0
48 12                           0                            15      6
49 0       W = 121.5; p = 0.425 3       W = 139.0; p = 0.427 2       2
50 1                            2                            1       0
51 12                           11                           12      4
52 2       W = 103.5; p = 0.493 2       W = 122.0; p = 0.948 1       1
53 1                            1                            2       0
54 12                           13                           12      5
55 0       W = 83.5; p = 0.719  1       W = 104.5; p = 1.000 1       2
56 4                            3                            4       1
57 9                            10                           10      3
58 1       —                    —       —                    1       3
59 1                            —                            1       0
60 12                           —                            13      3
61 —       —                    10      —                    —       —
62 —                            2                            —       —
63 —                            2                            —       —
64 —       —                    8       —                    —       —
65 —                            2                            —       —
66 —                            4                            —       —
67 —       —                    —       —                    3       —
68 —                            —                            6       —
69 —                            —                            0       —
70 —                            —                            1       —
71 —                            —                            2       —
72 —                            —                            1       —
73 —                            —                            0       —
74 —                            —                            2       —
75 —       —                    —       —                    0       —
76 —                            —                            3       —
77 —                            —                            3       —
78 —                            —                            6       —
79 —                            —                            1       —
80 —                            —                            2       —
81 —       —                    —       —                    11      —
82 —                            —                            9       —
83 —                            —                            13      —
84 —                            —                            11      —
85 —                            —                            9       —
86 —                            —                            10      —
87 —                            —                            7       —
88 —                            —                            9       —
89 —                            —                            9       —
90 —                            —                            11      —
91 —                            —                            8       —
92 —                            —                            8       —
93 —                            —                            9       —
94 —                            —                            8       —
   xforce_T1→T2        xforce_T2 xforce_T2→T3        xforce_T3
1  W = 28.5; p = 0.096 4         W = 3.5; p = 0.179  1
2                      1                             0
3                      1                             2
4  W = 32.0; p = 0.023 5         W = 6.5; p = 0.583  2
5                      1                             0
6                      0                             1
7  W = 23.0; p = 0.418 4         W = 6.0; p = 0.477  2
8                      2                             0
9                      0                             1
10 W = 23.5; p = 0.410 3         W = 11.0; p = 0.684 2
11                     2                             0
12                     1                             1
13 W = 8.0; p = 0.091  6         W = 15.0; p = 0.101 0
14                     0                             0
15                     0                             3
16 W = 22.0; p = 0.209 5         W = 9.0; p = 1.000  2
17                     0                             0
18                     1                             1
19 W = 8.0; p = 0.117  1         W = 11.5; p = 0.583 0
20                     1                             2
21                     4                             1
22 W = 16.5; p = 0.869 1         W = 10.0; p = 0.895 1
23                     1                             1
24                     4                             1
25 W = 20.0; p = 0.788 1         W = 4.0; p = 0.167  0
26                     1                             0
27                     4                             3
28 W = 10.0; p = 0.209 1         W = 5.0; p = 0.336  0
29                     1                             0
30                     4                             3
31 W = 19.0; p = 0.931 2         W = 4.5; p = 0.217  0
32                     0                             0
33                     4                             3
34 W = 25.5; p = 0.249 4         W = 8.5; p = 1.000  1
35                     0                             1
36                     2                             1
37 W = 19.5; p = 0.870 3         W = 12.5; p = 0.416 2
38                     1                             1
39                     2                             0
40 W = 19.5; p = 0.865 3         W = 13.5; p = 0.276 3
41                     0                             0
42                     3                             0
43 W = 16.5; p = 0.867 0         W = 11.0; p = 0.670 1
44                     2                             0
45                     4                             2
46 W = 13.5; p = 0.441 5         W = 10.0; p = 0.860 0
47                     1                             0
48                     0                             3
49 W = 17.0; p = 0.931 1         W = 11.0; p = 0.671 1
50                     1                             0
51                     4                             2
52 W = 13.5; p = 0.846 1         W = 6.0; p = 0.733  0
53                     1                             0
54                     3                             3
55 W = 14.5; p = 0.616 1         W = 8.0; p = 0.885  0
56                     0                             0
57                     5                             3
58 —                   —         —                   0
59                     —                             1
60                     —                             2
61 —                   3         —                   —
62                     1                             —
63                     2                             —
64 —                   4         —                   —
65                     1                             —
66                     1                             —
67 —                   —         —                   0
68                     —                             2
69                     —                             0
70                     —                             0
71                     —                             0
72                     —                             1
73                     —                             0
74                     —                             0
75 —                   —         —                   0
76                     —                             0
77                     —                             0
78                     —                             3
79                     —                             0
80                     —                             0
81 —                   —         —                   2
82                     —                             2
83                     —                             2
84                     —                             3
85                     —                             2
86                     —                             2
87                     —                             2
88                     —                             2
89                     —                             2
90                     —                             2
91                     —                             2
92                     —                             2
93                     —                             1
94                     —                             1

## §4 Table 4 - Inventário de Saúde Emocional (3 categorias)

Saúde Emocional: 216 respostas, sendo 172 da FINX (T1 = 86, T2 = 86) e 44 da Xforce (T1 = 25, T2 = 19). As respostas não podem ser pareadas entre as ondas, porque não há identificação do respondente. As coletas foram em dez/2025–jan/2026 (T1) e abr/2026 (T2).

Os principais resultados indicam:
- FINX: a liberdade para organizar as próprias atividades diminuiu de T1 para T2 (W = 4596.0; p < 0.001). "Muitas vezes/sempre" passou de 78/86 (91%) para 61/84 (73%).
- FINX: o encorajamento para usar criatividade e conhecimento diminuiu de T1 para T2 (W = 4342.0; p = 0.015). "Muitas vezes/sempre" passou de 69/86 (80%) para 61/84 (73%).
- Xforce: nenhum item teve diferença significativa entre T1 e T2 (p ≥ 0.05).

(risco) = item de risco: maior concordância/frequência indica maior risco.

In [5]:
tabela("emocional", agrupar = TRUE)

    Item
1   34. tem liberdade para organizar suas atividades? (ex.: escolher a ordem das tarefas)
2
3
4   35. e encorajado(a) a usar criatividade e conhecimento? (ex.: sugerir melhorias ou novas ideias)
5
6
7   4. cobra demais de si mesmo(a)? (ex.: sentir que nunca fez o suficiente) (risco)
8
9
10  31. sente-se satisfeito(a) consigo e com suas escolhas? (ex.: acreditar que esta seguindo o caminho certo)
11
12
13  1. consegue lidar bem com frustracoes e imprevistos? (ex.: manter a calma mesmo quando nao cumpre um prazo)
14
15
16  21. anda esquecido(a) ou com deficit de memoria? (ex.: esquecer compromissos ou nomes) (risco)
17
18
19  37. sente-se pertencente a equipe e a empresa? (ex.: sentir-se parte do grupo)
20
21
22  15. tem dores de cabeca ou dores musculares? (risco)
23
24
25  17. tem dificuldas para dormir? (risco)
26
27
28  45. recebe feedback para melhorar seu desempenho? (ex.: orientacoes claras e uteis)
29
30
31  16. costuma sentir-se cansado(a)? (ex.: acordar sem energia mesmo apos dormir) (risco)
32
33
34  44. sente-se a vontade para falar com sua lideranca? (ex.: expressar expectativas e conflitos sem medo)
35
36
37  47. sua lideranca demonstra preocupacao com seu bem-estar? (ex.: perguntar como voce esta e oferecer apoio)
38
39
40  26. costuma sentir ansiedade ou angustia? (ex.: sentir aperto no peito sem motivo claro) (risco)
41
42
43  32. esta satisfeito(a) com sua funcao atual? (ex.: sentir que exerce um papel adequado a voce)
44
45
46  27. tem queda de cabelo sem causa aparente? (risco)
47
48
49  48. sente-se valorizado(a) na empresa? (ex.: reconhecimento pelos resultados)
50
51
52  33. a empresa confia em sua capacidade de decisao? (ex.: resolver problemas sem pedir autorizacao para tudo)
53
54
55  2. mantem o autocontrole em situacoes de estresse ou conflito? (ex.: nao perder a cabeca em discussoes)
56
57
58  25. tem falta ou excesso de apetite? (ex.: assaltar a geladeira a noite ou pular refeicoes) (risco)
59
60
61  30. tem vontade de desistir de viver? (ex.: pensamentos sobre morte ou nao continuar) (risco)
62
63
64  3. consegue ser assertivo sem elevar o tom de voz ou ser agressivo? (ex.: falar o que precisa sem gritar)
65
66
67  41. este e um lugar psicologicamente saudavel? (ex.: trabalhar sem medo constante ou tensao excessiva)
68
69
70  6. sofre por antecipacao? (ex.: preocupar-se com algo que ainda nem aconteceu) (risco)
71
72
73  28. tem pensamentos perturbadores? (ex.: imaginar cenarios negativos ou pensamentos angustiantes) (risco)
74
75
76  24. percebe diminuicao da libido? (ex.: perda de interesse sexual) (risco)
77
78
79  22. tem dores de estomago ou problemas intestinais? (risco)
80
81
82  10. considera-se timido(a) ou inseguro(a)? (risco)
83
84
85  49. tem orgulho em trabalhar nesta empresa? (ex.: falar bem do local para outras pessoas)
86
87
88  36. os colaboradores se respeitam e se preocupam uns com os outros? (ex.: ausencia de humilhacao ou competicao toxica)
89
90
91  23. tem sentimentos de inferioridade? (ex.: acreditar que nao e bom o bastante) (risco)
92
93
94  38. existe senso de equipe? (ex.: colaboracao entre os profissionais)
95
96
97  7. remoi situacoes do passado? (ex.: lembrar com frequencia de magoas antigas) (risco)
98
99
100 39. ja sofreu assedio nesta empresa? (ex.: gritos, piadas, humilhacoes ou bullying) (risco)
101
102
103 9. sente algum tipo de fobia social? (ex.: medo de falar em publico) (risco)
104
105
106 18. sente-se desmotivado(a) ou desanimado(a)? (ex.: sem vontade de iniciar tarefas simples) (risco)
107
108
109 19. percebe-se triste ou com humor depressivo? (ex.: falta de prazer nas atividades diarias) (risco)
110
111
112 42. todos sao bem tratados independentemente de diferencas pessoais? (ex.: ausencia de preconceito por idade, genero ou etnia)
113
114
115 20. costuma ter dificuldade de concentracao? (ex.: iniciar tarefas e nao concluir) (risco)
116
117
118 46. recebe treinamentos adequados? (ex.: aprender o necessario para cumprir suas funcoes)
119
120
121 29. tem chorado mais ultimamente? (ex.: chorar por situacoes pequenas) (risco)
122
123
124 40. os colaboradores possuem as mesmas oportunidades? (ex.: promocoes sem favoritismo)
125
126
127 43. tem acesso aos equipamentoe e materiais adequados para desempenhar suas tarefas?
128
129
130 5. cobra demais dos outros? (ex.: esperar que as pessoas ajam como voce) (risco)
131
132
133 8. valoriza excessivamente a opiniao dos outros? (risco)
134
135
136 11. tem dificuldade em conviver com pessoas mais lentas? (ex.: ficar irritado quando alguem demora para entender algo) (risco)
137
138
139 12. ja se automutilou? (ex.: se machucar fisicamente para aliviar dor emocional) (risco)
140
141
142 13. sofre por padroes de beleza ou sucesso? (ex.: sentir-se inadequado por sua aparencia ou carreira) (risco)
143
144
145 14. sente-se intoxicado digitalmente? (ex.: passar muitas horas no celular) (risco)
146
147
148 50. o nivel de autonomia que possui atualmente na empresa, afeta negativamente sua saude emocional/mental? (risco)
149
150
151 51. o nivel de relacionamento e cooperacao entre colaboradores e equipes afeta negativamente sua saude emocional/mental? (risco)
152
153
154 52. o clima organizacional da empresa impacta negativamente sua saude emocional/mental? (risco)
155
156
157 53. a atuacao de sua lideranca tem impactado negativamente sua saude emocional/mental? (risco)
158
159
160 54. consegue separar suas atividades profissionais com sua vida pessoal?
161
162
163 55. o que mais lhe atrai em trabalhar nesta empresa? (pode assinalar mais de uma alternativa)
164
165
166
167
168 56. acha importante que sua empresa invista em um programa de prevencao de transtornos emocionais?
169
170 57. ha quanto esta atuando nessa empresa?
171
172
173
174
175
176 58. setor de atuacao:
177
178
179
180 59. assinale quais foram as jornadas de ouro quinzenal que voce participou:
181
182
183
184
185
186
187
188
189
    Resposta                                                            finx_T1
1   (1) nunca/raramente                                                 3
2   (2) as vezes                                                        5
3   (3) muitas vezes/sempre                                             78
4   (1) nunca/raramente                                                 6
5   (2) as vezes                                                        11
6   (3) muitas vezes/sempre                                             69
7   (1) nunca/raramente                                                 3
8   (2) as vezes                                                        14
9   (3) muitas vezes/sempre                                             69
10  (1) nunca/raramente                                                 7
11  (2) as vezes                                                        28
12  (3) muitas vezes/sempre                                             51
13  (1) nunca/raramente                                                 12
14  (2) as vezes                                                        28
15  (3) muitas vezes/sempre                                             46
16  (1) nunca/raramente                                                 26
17  (2) as vezes                                                        32
18  (3) muitas vezes/sempre                                             27
19  (1) nunca/raramente                                                 1
20  (2) as vezes                                                        9
21  (3) muitas vezes/sempre                                             76
22  (1) nunca/raramente                                                 26
23  (2) as vezes                                                        19
24  (3) muitas vezes/sempre                                             40
25  (1) nunca/raramente                                                 37
26  (2) as vezes                                                        24
27  (3) muitas vezes/sempre                                             25
28  (1) nunca/raramente                                                 8
29  (2) as vezes                                                        12
30  (3) muitas vezes/sempre                                             66
31  (1) nunca/raramente                                                 15
32  (2) as vezes                                                        21
33  (3) muitas vezes/sempre                                             50
34  (1) nunca/raramente                                                 4
35  (2) as vezes                                                        11
36  (3) muitas vezes/sempre                                             71
37  (1) nunca/raramente                                                 11
38  (2) as vezes                                                        14
39  (3) muitas vezes/sempre                                             61
40  (1) nunca/raramente                                                 28
41  (2) as vezes                                                        19
42  (3) muitas vezes/sempre                                             39
43  (1) nunca/raramente                                                 6
44  (2) as vezes                                                        18
45  (3) muitas vezes/sempre                                             62
46  (1) nunca/raramente                                                 40
47  (2) as vezes                                                        19
48  (3) muitas vezes/sempre                                             27
49  (1) nunca/raramente                                                 13
50  (2) as vezes                                                        16
51  (3) muitas vezes/sempre                                             57
52  (1) nunca/raramente                                                 8
53  (2) as vezes                                                        19
54  (3) muitas vezes/sempre                                             59
55  (1) nunca/raramente                                                 3
56  (2) as vezes                                                        23
57  (3) muitas vezes/sempre                                             60
58  (1) nunca/raramente                                                 29
59  (2) as vezes                                                        19
60  (3) muitas vezes/sempre                                             38
61  (1) nunca/raramente                                                 65
62  (2) as vezes                                                        13
63  (3) muitas vezes/sempre                                             8
64  (1) nunca/raramente                                                 3
65  (2) as vezes                                                        11
66  (3) muitas vezes/sempre                                             72
67  (1) nunca/raramente                                                 18
68  (2) as vezes                                                        24
69  (3) muitas vezes/sempre                                             44
70  (1) nunca/raramente                                                 11
71  (2) as vezes                                                        18
72  (3) muitas vezes/sempre                                             57
73  (1) nunca/raramente                                                 42
74  (2) as vezes                                                        16
75  (3) muitas vezes/sempre                                             28
76  (1) nunca/raramente                                                 41
77  (2) as vezes                                                        26
78  (3) muitas vezes/sempre                                             19
79  (1) nunca/raramente                                                 52
80  (2) as vezes                                                        20
81  (3) muitas vezes/sempre                                             14
82  (1) nunca/raramente                                                 43
83  (2) as vezes                                                        21
84  (3) muitas vezes/sempre                                             22
85  (1) nunca/raramente                                                 4
86  (2) as vezes                                                        9
87  (3) muitas vezes/sempre                                             73
88  (1) nunca/raramente                                                 4
89  (2) as vezes                                                        11
90  (3) muitas vezes/sempre                                             70
91  (1) nunca/raramente                                                 36
92  (2) as vezes                                                        24
93  (3) muitas vezes/sempre                                             26
94  (1) nunca/raramente                                                 1
95  (2) as vezes                                                        12
96  (3) muitas vezes/sempre                                             73
97  (1) nunca/raramente                                                 30
98  (2) as vezes                                                        24
99  (3) muitas vezes/sempre                                             32
100 (1) nunca/raramente                                                 77
101 (2) as vezes                                                        3
102 (3) muitas vezes/sempre                                             6
103 (1) nunca/raramente                                                 47
104 (2) as vezes                                                        17
105 (3) muitas vezes/sempre                                             22
106 (1) nunca/raramente                                                 34
107 (2) as vezes                                                        34
108 (3) muitas vezes/sempre                                             18
109 (1) nunca/raramente                                                 44
110 (2) as vezes                                                        22
111 (3) muitas vezes/sempre                                             20
112 (1) nunca/raramente                                                 5
113 (2) as vezes                                                        9
114 (3) muitas vezes/sempre                                             72
115 (1) nunca/raramente                                                 39
116 (2) as vezes                                                        29
117 (3) muitas vezes/sempre                                             18
118 (1) nunca/raramente                                                 8
119 (2) as vezes                                                        12
120 (3) muitas vezes/sempre                                             66
121 (1) nunca/raramente                                                 50
122 (2) as vezes                                                        16
123 (3) muitas vezes/sempre                                             20
124 (1) nunca/raramente                                                 12
125 (2) as vezes                                                        22
126 (3) muitas vezes/sempre                                             52
127 (1) nunca/raramente                                                 0
128 (2) as vezes                                                        4
129 (3) muitas vezes/sempre                                             82
130 (1) nunca/raramente                                                 27
131 (2) as vezes                                                        29
132 (3) muitas vezes/sempre                                             30
133 (1) nunca/raramente                                                 34
134 (2) as vezes                                                        22
135 (3) muitas vezes/sempre                                             30
136 (1) nunca/raramente                                                 29
137 (2) as vezes                                                        34
138 (3) muitas vezes/sempre                                             22
139 (1) nunca/raramente                                                 74
140 (2) as vezes                                                        6
141 (3) muitas vezes/sempre                                             6
142 (1) nunca/raramente                                                 49
143 (2) as vezes                                                        22
144 (3) muitas vezes/sempre                                             15
145 (1) nunca/raramente                                                 33
146 (2) as vezes                                                        28
147 (3) muitas vezes/sempre                                             25
148 (1) nunca/raramente                                                 —
149 (2) as vezes                                                        —
150 (3) muitas vezes/sempre                                             —
151 (1) nunca/raramente                                                 —
152 (2) as vezes                                                        —
153 (3) muitas vezes/sempre                                             —
154 (1) nunca/raramente                                                 —
155 (2) as vezes                                                        —
156 (3) muitas vezes/sempre                                             —
157 (1) nunca/raramente                                                 —
158 (2) as vezes                                                        —
159 (3) muitas vezes/sempre                                             —
160 (1) nunca/raramente                                                 —
161 (2) as vezes                                                        —
162 (3) muitas vezes/sempre                                             —
163 (1) salario / beneficios                                            54
164 (2) clima organizacional                                            42
165 (3) colegas de trabalho                                             46
166 (4) oportunidade de crescimento                                     47
167 (5) reconhecimento                                                  37
168 (1) sim                                                             83
169 (2) nao                                                             1
170 (1) ate 6 meses                                                     39
171 (2) de 6 meses a 1 ano                                              16
172 (3) de 1 ano a 2 anos                                               9
173 (4) de 2 anos a 4 anos                                              12
174 (5) 4 anos a 6 anos                                                 7
175 (6) mais de 6 anos                                                  2
176 (1) administrativo / financeiro                                     —
177 (2) apoio / servicos gerais                                         —
178 (3) comercial / atendimento                                         —
179 (4) operacional / producao                                          —
180 (1) 1ª semana - ferramenta: a mente mente                           —
181 (2) 2ª semana - historia: a mente mente                             —
182 (3) 3ª semana - ferramenta: mudar a era do apontamento de falhas    —
183 (4) 4ª semana - historia: mudar a era do apontamento de falhas      —
184 (5) 5ª semana - ferramenta: contemplar o belo                       —
185 (6) 6ª semana - historia: contemplar o belo                         —
186 (7) 7ª semana - ferramenta: de sempre uma nova chance para si mesmo —
187 (8) 8ª semana - historia: de sempre uma nova chance para si mesmo   —