Version control: 2026-10-14 - 18:30
Luis Anunciacao, PhD

# DA - AGEM Time Series

Loads `df.rds` from the DP notebook. Nothing is transformed here.

**Tests.** Two-sided Wilcoxon rank-sum (Mann-Whitney U) tests between consecutive waves, by company, for scale items. Waves are independent samples: SurveyMonkey collected no respondent ID, so answers cannot be paired. Lideres T2 items 6 and 20 are reverse-coded for the tests only (DP §2); counts are raw. "—" = item not applied in that wave.

In [1]:
pacman::p_load(tidyverse)

options(repr.matrix.max.rows = 400, repr.matrix.max.cols = 20)

# DP output from GitHub (Processing and analysis/Importable data/df.rds); private repository, token from the git credential store (gitcreds)
df <- readRDS(gzcon(curl::curl("https://raw.githubusercontent.com/anovabr/AGEM-Time-Series/main/Processing%20and%20analysis/Importable%20data/df.rds",
                               handle = curl::new_handle() |> curl::handle_setheaders(Authorization = paste("token", gitcreds::gitcreds_get()$password)))))

# item x response frequency table by company and wave, with W and p of the rank-sum test (T1 vs T2, T2 vs T3) on the first row of each item
tabela <- function(inst) {
  d <- filter(df, instrumento == inst)
  attr(df, "opcoes") |>
    filter(instrumento == inst) |>
    inner_join(distinct(d, item, empresa, onda), by = "item", relationship = "many-to-many") |>
    left_join(count(d, item, codigo, empresa, onda), by = c("item", "codigo", "empresa", "onda")) |>
    mutate(n = as.character(replace_na(n, 0L))) |>
    bind_rows(d |>
                filter(!is.na(valor_teste)) |>
                reframe(map_dfr(list(c("T1", "T2"), c("T2", "T3")), \(w) if (all(w %in% onda))
                          tibble(par = paste0(w[1], "\u2192", w[2]),
                                 n = with(suppressWarnings(wilcox.test(valor_teste[onda == w[1]], valor_teste[onda == w[2]])), sprintf("W = %.1f; p = %.3f", statistic, p.value)))),
                        .by = c(item, empresa)) |>
                transmute(item, empresa, onda = par, n, codigo = 1L)) |>
    pivot_wider(id_cols = c(item, codigo), names_from = c(empresa, onda), values_from = n, names_sort = TRUE) |>
    arrange(item, codigo) |>
    left_join(distinct(d, item, item_texto), by = "item") |>
    left_join(filter(attr(df, "opcoes"), instrumento == inst) |> select(item, codigo, resposta), by = c("item", "codigo")) |>
    mutate(Item = if_else(codigo == 1, paste0(item, ". ", item_texto), ""), Resposta = paste0("(", codigo, ") ", resposta),
           across(-c(item, codigo, item_texto, resposta, Item, Resposta), ~ if_else(is.na(.) & (!str_detect(cur_column(), "\u2192") | codigo == 1), "\u2014", replace_na(., "")))) |>
    (\(t) select(t, Item, Resposta, all_of(sort(setdiff(names(t), c("item", "codigo", "item_texto", "resposta", "Item", "Resposta"))))))()
}

## §1 Table 1 - Inventário de Saúde Mental exclusivo para Líderes

In [2]:
tabela("lideres")

    Item
1   1. sinto que a carga de responsabilidade pelas decisoes e elevada.
2
3
4
5
6   2. tenho suporte adequado = (recursos/informacao) para tomar decisoes de forma segura.
7
8
9
10
11  3. ha clareza sobre minhas responsabilidades e limites de autoridade (ex.: sei ate onde posso decidir sozinho e quando preciso escalonar). (invertida)
12
13
14
15
16  4. trabalho alem do horario previsto devido as demandas da lideranca (ex.: responder mensagens fora do expediente, reunioes extras).
17
18
19
20
21  5. percebo pressao constante para entrega de resultados que exigem alto nivel de desempenho.
22
23
24
25
26  6. sinto-me preparado(a) e confiante para lidar com conflitos internos.
27
28
29
30
31  7. preciso intervir frequentemente em conflitos que desgastam minha rotina de trabalho.
32
33
34
35
36  8. sinto que minha equipe depende excessivamente de mim para resolver problemas simples (ex.: duvidas recorrentes que poderiam ser resolvidas sem supervisao direta).
37
38
39
40
41  9. estou satisfeito(a) com a performance geral da minha equipe.
42
43
44
45
46  10. minha equipe possui conhecimentos tecnicos adequados para exercer suas funcoes (ex.: dominio de ferramentas, processos, habilidades operacionais). (invertida)
47
48
49
50
51  11. minha equipe possui competencias comportamentais adequadas as demandas de trabalho (ex.: comunicacao, responsabilidade, colaboracao). (invertida)
52
53
54
55
56  12. a falta de preparo tecnico ou comportamental da equipe aumenta meu nivel de estresse.
57
58
59
60
61  13. tenho autonomia suficiente para organizar o trabalho da minha equipe (ex.: definir prazos, distribuir tarefas). (invertida)
62
63
64
65
66  14. recebo feedback e apoio da alta direcao quando necessario. (invertida)
67
68
69
70
71  15. tenho autonomia para contratar colaboradores quando identifico essa necessidade.
72
73
74
75
76  16. tenho autonomia para desligar colaboradores quando isso se faz necessario (seguindo politicas internas e processos formais.
77
78
79
80
81  17. as politicas internas da empresa permitem decisoes de gestao de pessoas com agilidade
82
83
84
85
86  18. sou exposto(a) com frequencia a reclamacoes, criticas ou conflitos emocionais relacionados a lideranca (ex.: clientes insatisfeitos, pressao de superiores ou equipe).
87
88
89
90
91  19. meu trabalho exige constante tomada de decisoes que afetam a seguranca, bem-estar ou desempenho de outras pessoas (ex.: realocar pessoas, dar feedback dificil, definir prioridades).
92
93
94
95
96  20. sinto-me preparado(a) para lidar com situacoes de sofrimento emocional, saude mental ou crise envolvendo membros da equipe (ex.: ansiedade, burnout, conflitos pessoais afetando o trabalho). (invertida)
97
98
99
100
101 21. o nivel de autonomia e o apoio que recebe da organizacao impacta negativamente minha saude mental e emocional.
102
103
104
105
106 22. o nivel de exposicao emocional que sou exposto atualmente, impacta minha saude mental e emocional.
107
108
109
110
111 23. em qual setor/departamento voce trabalha?
112
113
114
115
116
117
118
119 24. ha quanto tempo voce trabalha na empresa?
120
121
122
123
124
125 25. marque as jornadas que voce participou:
126
127
128
129
130
131
132
133
134
135
136
137
138
    Resposta
1   (1) discordo totalmente
2   (2) discordo parcialmente
3   (3) nem concordo nem discordo
4   (4) concordo parcialmente
5   (5) concordo totalmente
6   (1) discordo totalmente
7   (2) discordo parcialmente
8   (3) nem concordo nem discordo
9   (4) concordo parcialmente
10  (5) concordo totalmente
11  (1) discordo totalmente
12  (2) discordo parcialmente
13  (3) nem concordo nem discordo
14  (4) concordo parcialmente
15  (5) concordo totalmente
16  (1) discordo totalmente
17  (2) discordo parcialmente
18  (3) nem concordo nem discordo
19  (4) concordo parcialmente
20  (5) concordo totalmente
21  (1) discordo totalmente
22  (2) discordo parcialmente
23  (3) nem concordo nem discordo
24  (4) concordo parcialmente
25  (5) concordo totalmente
26  (1) discordo totalmente
27  (2) discordo parcialmente
28  (3) nem concordo nem discordo
29  (4) concordo parcialmente
30  (5) concordo totalmente
31  (1) discordo totalmente
32  (2) discordo parcialmente
33  (3) nem concordo nem discordo
34  (4) concordo parcialmente
35  (5) concordo totalmente
36  (1) discordo totalmente
37  (2) discordo parcialmente
38  (3) nem concordo nem discordo
39  (4) concordo parcialmente
40  (5) concordo totalmente
41  (1) discordo totalmente
42  (2) discordo parcialmente
43  (3) nem concordo nem discordo
44  (4) concordo parcialmente
45  (5) concordo totalmente
46  (1) discordo totalmente
47  (2) discordo parcialmente
48  (3) nem concordo nem discordo
49  (4) concordo parcialmente
50  (5) concordo totalmente
51  (1) discordo totalmente
52  (2) discordo parcialmente
53  (3) nem concordo nem discordo
54  (4) concordo parcialmente
55  (5) concordo totalmente
56  (1) discordo totalmente
57  (2) discordo parcialmente
58  (3) nem concordo nem discordo
59  (4) concordo parcialmente
60  (5) concordo totalmente
61  (1) discordo totalmente
62  (2) discordo parcialmente
63  (3) nem concordo nem discordo
64  (4) concordo parcialmente
65  (5) concordo totalmente
66  (1) discordo totalmente
67  (2) discordo parcialmente
68  (3) nem concordo nem discordo
69  (4) concordo parcialmente
70  (5) concordo totalmente
71  (1) discordo totalmente
72  (2) discordo parcialmente
73  (3) nem concordo nem discordo
74  (4) concordo parcialmente
75  (5) concordo totalmente
76  (1) discordo totalmente
77  (2) discordo parcialmente
78  (3) nem concordo nem discordo
79  (4) concordo parcialmente
80  (5) concordo totalmente
81  (1) discordo totalmente
82  (2) discordo parcialmente
83  (3) nem concordo nem discordo
84  (4) concordo parcialmente
85  (5) concordo totalmente
86  (1) discordo totalmente
87  (2) discordo parcialmente
88  (3) nem concordo nem discordo
89  (4) concordo parcialmente
90  (5) concordo totalmente
91  (1) discordo totalmente
92  (2) discordo parcialmente
93  (3) nem concordo nem discordo
94  (4) concordo parcialmente
95  (5) concordo totalmente
96  (1) discordo totalmente
97  (2) discordo parcialmente
98  (3) nem concordo nem discordo
99  (4) concordo parcialmente
100 (5) concordo totalmente
101 (1) discordo totalmente
102 (2) discordo parcialmente
103 (3) nem concordo nem discordo
104 (4) concordo parcialmente
105 (5) concordo totalmente
106 (1) discordo totalmente
107 (2) discordo parcialmente
108 (3) nem concordo nem discordo
109 (4) concordo parcialmente
110 (5) concordo totalmente
111 (1) administrativo
112 (2) comercial/vendas
113 (3) financeiro
114 (4) recursos humanos
115 (5) operacional/producao
116 (6) marketing
117 (7) tecnologia/informatica
118 (8) outro (especifique)
119 (1) menos de 3 meses
120 (2) de 3 a 6 meses
121 (3) de 6 meses a 1 ano
122 (4) de 1 a 3 anos
123 (5) de 3 a 5 anos
124 (6) mais de 5 anos
125 (1) a mente "mente"
126 (2) mudar a era do apontamento de falhas para a era da celebracao dos acertos
127 (3) contemplar o belo
128 (4) de sempre uma nova chance para si mesmo
129 (5) expor e nao impor ideias
130 (6) pensar antes de agir e reagir
131 (7) ninguem da o que nao tem
132 (8) circuito fechado da memoria
133 (9) tecnica do d.c.d.
134 (10) armadilhas da mente
135 (11) o caminho mudou - armadilha do conformismo
136 (12) armadilha da catastrofizacao
137 (13) armadilha da comparacao
138 (14) armadilha do medo de errar e do excesso de confianca
    finx_T1 finx_T1→T2           finx_T2 finx_T2→T3           finx_T3 xforce_T1
1   3       W = 90.5; p = 0.237  4       W = 94.5; p = 0.305  2       1
2   5                            0                            2       1
3   5                            5                            3       2
4   0                            7                            4       2
5   2                            0                            4       0
6   0       W = 127.5; p = 0.766 0       W = 128.0; p = 0.752 1       0
7   2                            2                            1       1
8   2                            2                            1       1
9   3                            5                            7       3
10  8                            7                            5       1
11  0       W = 103.5; p = 0.493 0       W = 122.0; p = 0.948 0       0
12  2                            2                            1       1
13  1                            1                            2       0
14  6                            4                            4       3
15  6                            9                            8       2
16  3       W = 136.5; p = 0.515 6       W = 72.5; p = 0.057  1       3
17  5                            2                            4       0
18  1                            3                            1       1
19  4                            4                            5       1
20  2                            1                            4       1
21  2       W = 164.5; p = 0.073 6       W = 27.5; p = 0.000  0       1
22  3                            4                            1       0
23  4                            3                            3       1
24  5                            3                            4       3
25  1                            0                            7       1
26  0       W = 102.0; p = 0.413 11      W = 130.5; p = 0.634 0       0
27  1                            5                            0       0
28  2                            0                            0       0
29  3                            0                            6       3
30  9                            0                            9       3
31  6       W = 106.5; p = 0.587 7       W = 93.0; p = 0.276  3       0
32  6                            3                            3       1
33  3                            3                            7       4
34  0                            3                            1       1
35  0                            0                            1       0
36  4       W = 75.0; p = 0.085  2       W = 120.5; p = 1.000 3       0
37  9                            9                            7       2
38  1                            3                            2       2
39  0                            2                            2       1
40  0                            0                            1       1
41  1       W = 117.5; p = 0.826 0       W = 101.5; p = 0.448 0       1
42  2                            3                            2       2
43  1                            1                            1       0
44  4                            7                            5       3
45  6                            5                            7       0
46  0       —                    —       —                    0       0
47  1                            —                            1       3
48  1                            —                            1       0
49  6                            —                            7       2
50  6                            —                            6       1
51  0       W = 121.5; p = 0.425 0       W = 139.0; p = 0.427 1       0
52  0                            3                            1       2
53  1                            2                            1       0
54  7                            5                            11      3
55  5                            6                            1       1
56  3       W = 102.0; p = 0.595 5       W = 89.0; p = 0.483  4       2
57  5                            4                            4       0
58  3                            4                            4       0
59  1                            0                            3       3
60  1                            1                            0       1
61  0       W = 89.5; p = 0.952  0       W = 127.0; p = 0.277 1       0
62  0                            1                            2       1
63  1                            0                            0       2
64  3                            3                            4       1
65  9                            10                           8       2
66  1       W = 81.5; p = 0.652  1       W = 112.5; p = 0.753 2       0
67  2                            3                            1       1
68  3                            1                            5       1
69  4                            4                            2       1
70  3                            5                            5       3
71  1       W = 58.5; p = 0.184  1       W = 131.0; p = 0.253 3       2
72  5                            2                            1       2
73  3                            3                            5       1
74  0                            3                            4       1
75  3                            5                            2       0
76  0       W = 112.0; p = 0.132 1       W = 82.5; p = 0.312  1       2
77  0                            2                            0       1
78  2                            3                            2       0
79  3                            3                            5       1
80  7                            5                            7       2
81  0       W = 83.5; p = 0.719  0       W = 104.5; p = 1.000 0       0
82  0                            1                            1       2
83  4                            3                            4       1
84  6                            5                            4       1
85  3                            5                            6       2
86  9       W = 81.0; p = 0.580  9       W = 68.5; p = 0.094  4       1
87  3                            1                            5       0
88  1                            4                            4       1
89  0                            0                            1       3
90  0                            0                            1       0
91  2       W = 107.0; p = 0.441 5       W = 77.5; p = 0.226  3       0
92  4                            1                            2       1
93  2                            5                            3       1
94  3                            2                            4       2
95  2                            1                            3       2
96  1       W = 96.0; p = 0.819  3       W = 108.0; p = 0.908 1       0
97  2                            5                            3       0
98  1                            3                            1       1
99  6                            3                            8       4
100 3                            0                            2       1
101 —       —                    10      —                    —       —
102 —                            0                            —       —
103 —                            2                            —       —
104 —                            2                            —       —
105 —                            0                            —       —
106 —       —                    6       —                    —       —
107 —                            2                            —       —
108 —                            2                            —       —
109 —                            3                            —       —
110 —                            1                            —       —
111 —       —                    —       —                    3       —
112 —                            —                            6       —
113 —                            —                            0       —
114 —                            —                            1       —
115 —                            —                            2       —
116 —                            —                            1       —
117 —                            —                            0       —
118 —                            —                            2       —
119 —       —                    —       —                    0       —
120 —                            —                            3       —
121 —                            —                            3       —
122 —                            —                            6       —
123 —                            —                            1       —
124 —                            —                            2       —
125 —       —                    —       —                    11      —
126 —                            —                            9       —
127 —                            —                            13      —
128 —                            —                            11      —
129 —                            —                            9       —
130 —                            —                            10      —
131 —                            —                            7       —
132 —                            —                            9       —
133 —                            —                            9       —
134 —                            —                            11      —
135 —                            —                            8       —
136 —                            —                            8       —
137 —                            —                            9       —
138 —                            —                            8       —
    xforce_T1→T2        xforce_T2 xforce_T2→T3        xforce_T3
1   W = 19.5; p = 0.870 2         W = 12.5; p = 0.416 2
2                       1                             0
3                       1                             1
4                       1                             0
5                       1                             0
6   W = 20.0; p = 0.788 0         W = 4.0; p = 0.167  0
7                       1                             0
8                       1                             0
9                       4                             2
10                      0                             1
11  W = 13.5; p = 0.846 0         W = 6.0; p = 0.733  0
12                      1                             0
13                      1                             0
14                      0                             1
15                      3                             2
16  W = 23.0; p = 0.418 4         W = 6.0; p = 0.477  1
17                      0                             1
18                      2                             0
19                      0                             1
20                      0                             0
21  W = 28.5; p = 0.096 3         W = 3.5; p = 0.179  0
22                      1                             1
23                      1                             0
24                      1                             2
25                      0                             0
26  W = 13.5; p = 0.441 5         W = 10.0; p = 0.860 0
27                      0                             0
28                      1                             0
29                      0                             1
30                      0                             2
31  W = 32.0; p = 0.023 3         W = 6.5; p = 0.583  1
32                      2                             1
33                      1                             0
34                      0                             1
35                      0                             0
36  W = 23.5; p = 0.410 2         W = 11.0; p = 0.684 2
37                      1                             0
38                      2                             0
39                      0                             1
40                      1                             0
41  W = 10.0; p = 0.209 0         W = 5.0; p = 0.336  0
42                      1                             0
43                      1                             0
44                      2                             1

## §2 Table 2 - Inventário de Saúde Emocional

In [3]:
tabela("emocional")

    Item
1   1. consegue lidar bem com frustracoes e imprevistos? (ex.: manter a calma mesmo quando nao cumpre um prazo)
2
3
4
5
6   2. mantem o autocontrole em situacoes de estresse ou conflito? (ex.: nao perder a cabeca em discussoes)
7
8
9
10
11  3. consegue ser assertivo sem elevar o tom de voz ou ser agressivo? (ex.: falar o que precisa sem gritar)
12
13
14
15
16  4. cobra demais de si mesmo(a)? (ex.: sentir que nunca fez o suficiente)
17
18
19
20
21  5. cobra demais dos outros? (ex.: esperar que as pessoas ajam como voce)
22
23
24
25
26  6. sofre por antecipacao? (ex.: preocupar-se com algo que ainda nem aconteceu)
27
28
29
30
31  7. remoi situacoes do passado? (ex.: lembrar com frequencia de magoas antigas)
32
33
34
35
36  8. valoriza excessivamente a opiniao dos outros?
37
38
39
40
41  9. sente algum tipo de fobia social? (ex.: medo de falar em publico)
42
43
44
45
46  10. considera-se timido(a) ou inseguro(a)?
47
48
49
50
51  11. tem dificuldade em conviver com pessoas mais lentas? (ex.: ficar irritado quando alguem demora para entender algo)
52
53
54
55
56  12. ja se automutilou? (ex.: se machucar fisicamente para aliviar dor emocional)
57
58
59
60
61  13. sofre por padroes de beleza ou sucesso? (ex.: sentir-se inadequado por sua aparencia ou carreira)
62
63
64
65
66  14. sente-se intoxicado digitalmente? (ex.: passar muitas horas no celular)
67
68
69
70
71  15. tem dores de cabeca ou dores musculares?
72
73
74
75
76  16. costuma sentir-se cansado(a)? (ex.: acordar sem energia mesmo apos dormir)
77
78
79
80
81  17. tem dificuldas para dormir?
82
83
84
85
86  18. sente-se desmotivado(a) ou desanimado(a)? (ex.: sem vontade de iniciar tarefas simples)
87
88
89
90
91  19. percebe-se triste ou com humor depressivo? (ex.: falta de prazer nas atividades diarias)
92
93
94
95
96  20. costuma ter dificuldade de concentracao? (ex.: iniciar tarefas e nao concluir)
97
98
99
100
101 21. anda esquecido(a) ou com deficit de memoria? (ex.: esquecer compromissos ou nomes)
102
103
104
105
106 22. tem dores de estomago ou problemas intestinais?
107
108
109
110
111 23. tem sentimentos de inferioridade? (ex.: acreditar que nao e bom o bastante)
112
113
114
115
116 24. percebe diminuicao da libido? (ex.: perda de interesse sexual)
117
118
119
120
121 25. tem falta ou excesso de apetite? (ex.: assaltar a geladeira a noite ou pular refeicoes)
122
123
124
125
126 26. costuma sentir ansiedade ou angustia? (ex.: sentir aperto no peito sem motivo claro)
127
128
129
130
131 27. tem queda de cabelo sem causa aparente?
132
133
134
135
136 28. tem pensamentos perturbadores? (ex.: imaginar cenarios negativos ou pensamentos angustiantes)
137
138
139
140
141 29. tem chorado mais ultimamente? (ex.: chorar por situacoes pequenas)
142
143
144
145
146 30. tem vontade de desistir de viver? (ex.: pensamentos sobre morte ou nao continuar)
147
148
149
150
151 31. sente-se satisfeito(a) consigo e com suas escolhas? (ex.: acreditar que esta seguindo o caminho certo)
152
153
154
155
156 32. esta satisfeito(a) com sua funcao atual? (ex.: sentir que exerce um papel adequado a voce)
157
158
159
160
161 33. a empresa confia em sua capacidade de decisao? (ex.: resolver problemas sem pedir autorizacao para tudo)
162
163
164
165
166 34. tem liberdade para organizar suas atividades? (ex.: escolher a ordem das tarefas)
167
168
169
170
171 35. e encorajado(a) a usar criatividade e conhecimento? (ex.: sugerir melhorias ou novas ideias)
172
173
174
175
176 36. os colaboradores se respeitam e se preocupam uns com os outros? (ex.: ausencia de humilhacao ou competicao toxica)
177
178
179
180
181 37. sente-se pertencente a equipe e a empresa? (ex.: sentir-se parte do grupo)
182
183
184
185
186 38. existe senso de equipe? (ex.: colaboracao entre os profissionais)
187
188
189
190
191 39. ja sofreu assedio nesta empresa? (ex.: gritos, piadas, humilhacoes ou bullying)
192
193
194
195
196 40. os colaboradores possuem as mesmas oportunidades? (ex.: promocoes sem favoritismo)
197
198
199
200
201 41. este e um lugar psicologicamente saudavel? (ex.: trabalhar sem medo constante ou tensao excessiva)
202
203
204
205
206 42. todos sao bem tratados independentemente de diferencas pessoais? (ex.: ausencia de preconceito por idade, genero ou etnia)
207
208
209
210
211 43. tem acesso aos equipamentoe e materiais adequados para desempenhar suas tarefas?
212
213
214
215
216 44. sente-se a vontade para falar com sua lideranca? (ex.: expressar expectativas e conflitos sem medo)
217
218
219
220
221 45. recebe feedback para melhorar seu desempenho? (ex.: orientacoes claras e uteis)
222
223
224
225
226 46. recebe treinamentos adequados? (ex.: aprender o necessario para cumprir suas funcoes)
227
228
229
230
231 47. sua lideranca demonstra preocupacao com seu bem-estar? (ex.: perguntar como voce esta e oferecer apoio)
232
233
234
235
236 48. sente-se valorizado(a) na empresa? (ex.: reconhecimento pelos resultados)
237
238
239
240
241 49. tem orgulho em trabalhar nesta empresa? (ex.: falar bem do local para outras pessoas)
242
243
244
245
246 50. o nivel de autonomia que possui atualmente na empresa, afeta negativamente sua saude emocional/mental?
247
248
249
250
251 51. o nivel de relacionamento e cooperacao entre colaboradores e equipes afeta negativamente sua saude emocional/mental?
252
253
254
255
256 52. o clima organizacional da empresa impacta negativamente sua saude emocional/mental?
257
258
259
260
261 53. a atuacao de sua lideranca tem impactado negativamente sua saude emocional/mental?
262
263
264
265
266 54. consegue separar suas atividades profissionais com sua vida pessoal?
267
268
269
270
271 55. o que mais lhe atrai em trabalhar nesta empresa? (pode assinalar mais de uma alternativa)
272
273
274
275
276 56. acha importante que sua empresa invista em um programa de prevencao de transtornos emocionais?
277
278 57. ha quanto esta atuando nessa empresa?
279
280
281
282
283
284 58. setor de atuacao:
285
286
287
288 59. assinale quais foram as jornadas de ouro quinzenal que voce participou:
289
290
291
292
293
294
295
296
297
    Resposta                                                            finx_T1
1   (1) nunca                                                           0
2   (2) raramente                                                       12
3   (3) as vezes                                                        28
4   (4) muitas vezes                                                    39
5   (5) sempre                                                          7
6   (1) nunca                                                           0
7   (2) raramente                                                       3
8   (3) as vezes                                                        23
9   (4) muitas vezes                                                    41
10  (5) sempre                                                          19
11  (1) nunca                                                           1
12  (2) raramente                                                       2
13  (3) as vezes                                                        11
14  (4) muitas vezes                                                    47
15  (5) sempre                                                          25
16  (1) nunca                                                           0
17  (2) raramente                                                       3
18  (3) as vezes                                                        14
19  (4) muitas vezes                                                    26
20  (5) sempre                                                          43
21  (1) nunca                                                           4
22  (2) raramente                                                       23
23  (3) as vezes                                                        29
24  (4) muitas vezes                                                    26
25  (5) sempre                                                          4
26  (1) nunca                                                           2
27  (2) raramente                                                       9
28  (3) as vezes                                                        18
29  (4) muitas vezes                                                    28
30  (5) sempre                                                          29
31  (1) nunca                                                           6
32  (2) raramente                                                       24
33  (3) as vezes                                                        24
34  (4) muitas vezes                                                    19
35  (5) sempre                                                          13
36  (1) nunca                                                           6
37  (2) raramente                                                       28
38  (3) as vezes                                                        22
39  (4) muitas vezes                                                    23
40  (5) sempre                                                          7
41  (1) nunca                                                           27
42  (2) raramente                                                       20
43  (3) as vezes                                                        17
44  (4) muitas vezes                                                    13
45  (5) sempre                                                          9
46  (1) nunca                                                           18
47  (2) raramente                                                       25
48  (3) as vezes                                                        21
49  (4) muitas vezes                                                    15
50  (5) sempre                                                          7
51  (1) nunca                                                           10
52  (2) raramente                                                       19
53  (3) as vezes                                                        34
54  (4) muitas vezes                                                    13
55  (5) sempre                                                          9
56  (1) nunca                                                           64
57  (2) raramente                                                       10
58  (3) as vezes                                                        6
59  (4) muitas vezes                                                    6
60  (5) sempre                                                          0
61  (1) nunca                                                           25
62  (2) raramente                                                       24
63  (3) as vezes                                                        22
64  (4) muitas vezes                                                    10
65  (5) sempre                                                          5
66  (1) nunca                                                           8
67  (2) raramente                                                       25
68  (3) as vezes                                                        28
69  (4) muitas vezes                                                    21
70  (5) sempre                                                          4
71  (1) nunca                                                           4
72  (2) raramente                                                       22
73  (3) as vezes                                                        19
74  (4) muitas vezes                                                    23
75  (5) sempre                                                          17
76  (1) nunca                                                           4
77  (2) raramente                                                       11
78  (3) as vezes                                                        21
79  (4) muitas vezes                                                    34
80  (5) sempre                                                          16
81  (1) nunca                                                           13
82  (2) raramente                                                       24
83  (3) as vezes                                                        24
84  (4) muitas vezes                                                    17
85  (5) sempre                                                          8
86  (1) nunca                                                           9
87  (2) raramente                                                       25
88  (3) as vezes                                                        34
89  (4) muitas vezes                                                    14
90  (5) sempre                                                          4
91  (1) nunca                                                           15
92  (2) raramente                                                       29
93  (3) as vezes                                                        22
94  (4) muitas vezes                                                    15
95  (5) sempre                                                          5
96  (1) nunca                                                           10
97  (2) raramente                                                       29
98  (3) as vezes                                                        29
99  (4) muitas vezes                                                    13
100 (5) sempre                                                          5
101 (1) nunca                                                           8
102 (2) raramente                                                       18
103 (3) as vezes                                                        32
104 (4) muitas vezes                                                    17
105 (5) sempre                                                          10
106 (1) nunca                                                           21
107 (2) raramente                                                       31
108 (3) as vezes                                                        20
109 (4) muitas vezes                                                    10
110 (5) sempre                                                          4
111 (1) nunca                                                           18
112 (2) raramente                                                       18
113 (3) as vezes                                                        24
114 (4) muitas vezes                                                    16
115 (5) sempre                                                          10
116 (1) nunca                                                           21
117 (2) raramente                                                       20
118 (3) as vezes                                                        26
119 (4) muitas vezes                                                    16
120 (5) sempre                                                          3
121 (1) nunca                                                           13
122 (2) raramente                                                       16
123 (3) as vezes                                                        19
124 (4) muitas vezes                                                    25
125 (5) sempre                                                          13
126 (1) nunca                                                           11
127 (2) raramente                                                       17
128 (3) as vezes                                                        19
129 (4) muitas vezes                                                    24
130 (5) sempre                                                          15
131 (1) nunca                                                           28
132 (2) raramente                                                       12
133 (3) as vezes                                                        19
134 (4) muitas vezes                                                    12
135 (5) sempre                                                          15
136 (1) nunca                                                           23
137 (2) raramente                                                       19
138 (3) as vezes                                                        16
139 (4) muitas vezes                                                    15
140 (5) sempre                                                          13
141 (1) nunca                                                           30
142 (2) raramente                                                       20
143 (3) as vezes                                                        16
144 (4) muitas vezes                                                    8
145 (5) sempre                                                          12
146 (1) nunca                                                           52
147 (2) raramente                                                       13
148 (3) as vezes                                                        13
149 (4) muitas vezes                                                    2
150 (5) sempre                                                          6
151 (1) nunca                                                           1
152 (2) raramente                                                       6
153 (3) as vezes                                                        28
154 (4) muitas vezes                                                    37
155 (5) sempre                                                          14
156 (1) nunca                                                           1
157 (2) raramente                                                       5
158 (3) as vezes                                                        18
159 (4) muitas vezes                                                    37
160 (5) sempre                                                          25
161 (1) nunca                                                           2
162 (2) raramente                                                       6
163 (3) as vezes                                                        19
164 (4) muitas vezes                                                    44
165 (5) sempre                                                          15
166 (1) nunca                                                           0
167 (2) raramente                                                       3
168 (3) as vezes                                                        5
169 (4) muitas vezes                                                    40
170 (5) sempre                                                          38
171 (1) nunca                                                           1
172 (2) raramente                                                       5
173 (3) as vezes                                                        11
174 (4) muitas vezes                                                    30
175 (5) sempre                                                          39
176 (1) nunca                                                           0
177 (2) raramente                                                       4
178 (3) as vezes                                                        11
179 (4) muitas vezes                                                    33
180 (5) sempre                                                          37
181 (1) nunca                                                           0
182 (2) raramente                                                       1
183 (3) as vezes                                                        9
184 (4) muitas vezes                                                    34
185 (5) sempre                                                          42